name: flutter_agents
description: "Universal Production Flutter Template & Starter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Tools & Styling
  cupertino_icons: ^1.0.8
  reactive_forms: ^18.2.2
  flutter_svg: ^2.3.0
  blur: ^4.0.2

  # Localization
  intl: ^0.20.2
  intl_utils: ^2.8.14

  # Networking & HTTP
  dio: ^5.11.0
  retrofit: ^4.9.2

  # Code Generation Annotations
  json_annotation: ^4.12.0
  freezed_annotation: ^3.1.0
  copy_with_extension: ^17.0.0

  # State Management & Concurrency
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^11.0.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.1.0

  # Routing & Navigation
  auto_route: ^11.1.0

  # Dependency Injection
  get_it: ^9.2.1
  injectable: ^3.0.0

  # Persistence & Secure Storage
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

  # Code Generators
  build_runner: ^2.13.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  retrofit_generator: ^10.2.3
  auto_route_generator: ^10.5.0
  injectable_generator: ^3.0.2
  copy_with_extension_gen: ^17.0.0
  flutter_gen_runner: ^5.13.0+1
  flutter_launcher_icons: ^0.14.4

  # Testing Mocks
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/svgs/

# Assets & SVG Generator configuration (Strictly NO lib/gen)
flutter_gen:
  output: lib/presentation/ui_utils/assets
  integrations:
    flutter_svg: true

# Continuous import sorting configuration
import_sorter:
  comments: false
  ignored_files:
    - \.g\.dart
    - \.gr\.dart
    - \.freezed\.dart
    - \.config\.dart
    - lib/l10n/generated/.*

# Localization configuration
flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/l10n/generated
  arb_dir: lib/l10n


